version: "3.9"

services:
  db:
    image: postgres:16
    container_name: coworking_postgres
    restart: always
    environment:
      POSTGRES_DB: coworking
      POSTGRES_USER: coworking_user
      POSTGRES_PASSWORD: coworking_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: